version: '3.6'

services:

  dummy:
    build: dummy-service
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 2048M
##        reservations:
##          cpus: 0.25
##          memory: 128M
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

    depends_on:
      mysql-api:
        condition: service_healthy

  redis:
    image: redis:6.0.5
    command: redis-server --requirepass passwod --port 6379
    container_name: redis6379
    hostname: redis6379
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 2048M
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379

  mysql-api:
    image: mysql:5.7
#    mem_limit: 350m
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 2048M
    ports:
      - 3307:3307
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=trainerdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
      - MYSQL_TCP_PORT=3307
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uuser", "-ppwd", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10