spring.h2.console.enabled: true
spring.h2.console.path: /h2
spring.datasource.hikari.jdbc-url: jdbc:h2:~/test
spring.datasource.username: sa
spring.datasource.password:



spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true


logging:
  level:
    root: ERROR
    #INFO

#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace